tasks:
  # - name: start
- before: |
    pyenv virtualenv venv
    source activate venv
    pip install --upgrade pip
    pip install --upgrade setuptools
    
  init:  |
    echo "проверка init"
        
  command: python zero.py